#!/usr/bin/env python3
"""Prepare and validate a commit-bound pull-request body before PR creation."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from validate_author_review import SECTION, validate_author_review
from validate_c059 import read_commits, validate_commit, validate_pr_body
from validate_runtime_lifecycle_evidence import runtime_gate_required

AUTHOR_REVIEW = """## Author Review

<!-- Generated after final push by scripts/prepare_pr_body.py. -->
- [x] Reviewed the complete diff against the authorized scope
- [x] Reviewed test and quality-gate results
- [x] Reviewed security, constitutional, and rollback impact
- [x] Resolved every finding or recorded no findings

**Reviewed Commit:** {head}
**Author Review Result:** PASS

"""
RUNTIME_EVIDENCE_SECTION = re.compile(
    r"^## Pre-PR Runtime Evidence\s*$\n.*?(?=^##\s|\Z)",
    re.MULTILINE | re.DOTALL,
)


def git(*arguments: str) -> str:
    result = subprocess.run(  # noqa: S603
        ["git", *arguments],  # noqa: S607
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def authoritative_remote_head(remote: str) -> str:
    branch = git("branch", "--show-current")
    if not branch:
        raise ValueError("current checkout must be a named branch")
    remote_record = git("ls-remote", "--heads", remote, f"refs/heads/{branch}")
    if not remote_record:
        raise ValueError(f"branch {branch!r} is not pushed to {remote!r}")
    return remote_record.split(maxsplit=1)[0]


def prepare_body(body: str, head: str) -> str:
    match = SECTION.search(body)
    if match is None:
        raise ValueError("PR body must contain the `## Author Review` template section")
    return body[: match.start()] + AUTHOR_REVIEW.format(head=head) + body[match.end() :]


def add_runtime_evidence(body: str, evidence: dict[str, object]) -> str:
    if evidence.get("passed") is not True:
        raise ValueError("runtime lifecycle evidence must report passed=true")
    rendered = (
        "## Pre-PR Runtime Evidence\n\n"
        "Generated by `scripts/run_goal006_runtime_lifecycle_gate.sh` before PR creation.\n\n"
        "```json\n"
        f"{json.dumps(evidence, indent=2, sort_keys=True)}\n"
        "```\n\n"
    )
    match = RUNTIME_EVIDENCE_SECTION.search(body)
    if match is not None:
        return body[: match.start()] + rendered + body[match.end() :]
    author_review = SECTION.search(body)
    if author_review is None:
        raise ValueError("PR body must contain the `## Author Review` template section")
    return body[: author_review.start()] + rendered + body[author_review.start() :]


def run_runtime_gate(body_file: Path, head: str) -> dict[str, object]:
    repository_root = Path(git("rev-parse", "--show-toplevel"))
    evidence_file = body_file.with_suffix(".runtime-evidence.json")
    subprocess.run(  # noqa: S603
        [str(repository_root / "scripts/run_goal006_runtime_lifecycle_gate.sh"), str(evidence_file)],
        cwd=repository_root,
        check=True,
    )
    evidence = json.loads(evidence_file.read_text(encoding="utf-8"))
    if evidence.get("commit_sha") != head:
        raise ValueError("runtime lifecycle evidence is not bound to the pushed branch HEAD")
    return evidence


def validate_prepared_body(body: str, base: str, head: str) -> list[str]:
    violations = validate_pr_body(body)
    for subject, commit_body in read_commits(base, head):
        violations.extend(validate_commit(subject, commit_body))
    violations.extend(validate_author_review(body, head))
    return violations


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--body-file", required=True, type=Path)
    parser.add_argument("--base", default="origin/main")
    parser.add_argument("--remote", default="origin")
    arguments = parser.parse_args()

    try:
        local_head = git("rev-parse", "HEAD")
        remote_head = authoritative_remote_head(arguments.remote)
        if local_head != remote_head:
            raise ValueError(f"local HEAD {local_head} does not match pushed branch HEAD {remote_head}")
        body = arguments.body_file.read_text(encoding="utf-8")
        changed_files = git("diff", "--name-only", f"{arguments.base}..{remote_head}").splitlines()
        if runtime_gate_required(changed_files):
            body = add_runtime_evidence(body, run_runtime_gate(arguments.body_file, remote_head))
        body = prepare_body(body, remote_head)
        violations = validate_prepared_body(body, arguments.base, remote_head)
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        print(f"PR body preparation failed: {error}", file=sys.stderr)
        return 1

    if violations:
        print("PR body preparation failed:", file=sys.stderr)
        for violation in violations:
            print(f"- {violation}", file=sys.stderr)
        return 1

    arguments.body_file.write_text(body, encoding="utf-8")
    print(f"PR body prepared for pushed commit {remote_head}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
