// Implements: tests/QA-STRATEGY.md §5.1 Unit Tests
// constitutional_basis: C-076 (test coverage), C-082 (build validation)
// DETERMINISTIC: Grpc.Core.ServerCallContext abstract members are
// properties (NOT methods) — generated by template to prevent CS0505.

#nullable enable
// using directives MUST precede namespace — Grpc.Core conflicts with
// Waooaw.ConstitutionalEngine.Grpc (proto namespace) if placed after.
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Grpc.Core;

namespace Waooaw.ConstitutionalEngine.Tests.Evaluators;

/// <summary>
/// Concrete ServerCallContext for unit tests.
/// Moq cannot mock ServerCallContext (abstract protected members are non-virtual).
/// All abstract members are PROPERTIES — never override them as methods.
/// </summary>
public sealed class FakeServerCallContext : ServerCallContext
{
    private readonly Metadata _requestHeaders;
    private readonly Metadata _responseTrailers = new Metadata();
    private Status _status;
    private WriteOptions? _writeOptions = WriteOptions.Default;

    /// <summary>Create a context with optional x-tenant-id metadata.</summary>
    public static FakeServerCallContext Create(string? tenantId = null) =>
        new(tenantId is null
            ? new Metadata()
            : new Metadata { { "x-tenant-id", tenantId } });

    public FakeServerCallContext(Metadata? requestHeaders = null)
        => _requestHeaders = requestHeaders ?? new Metadata();

    // ── Abstract properties (NOT methods — CS0505 if you use () here) ────
    protected override string MethodCore
        => "/constitutional.v1.ConstitutionalService/ValidateAction";
    protected override string HostCore => "localhost";
    protected override DateTime DeadlineCore => DateTime.MaxValue;
    protected override Metadata RequestHeadersCore => _requestHeaders;
    protected override CancellationToken CancellationTokenCore
        => CancellationToken.None;
    protected override string PeerCore => "ipv4:127.0.0.1:50051";
    protected override Metadata ResponseTrailersCore => _responseTrailers;
    protected override AuthContext AuthContextCore
        => new AuthContext(null,
               new Dictionary<string, List<AuthProperty>>());

    // ── Abstract methods ────────────────────────────────────────────────
    protected override ContextPropagationToken CreatePropagationTokenCore(
        ContextPropagationOptions? options)
        => throw new NotImplementedException("Not required for unit tests.");

    protected override Task WriteResponseHeadersAsyncCore(
        Metadata responseHeaders)
        => Task.CompletedTask;

    // ── Abstract properties with setters ────────────────────────────────
    protected override Status StatusCore
    {
        get => _status;
        set => _status = value;
    }

    protected override WriteOptions? WriteOptionsCore
    {
        get => _writeOptions;
        set => _writeOptions = value;
    }
}
